2025-09-16 20:03:29|ERROR|Error.py|16|[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 154, in POST
    Lobby.SendMail(req)
  File "/home/py/share/webcppcluster2025/Lobby.py", line 55, in SendMail
    service.SendSvrd(Config.MAIL_HOST, Config.MAIL_PORT, mailproto.SerializeToString())
  File "/home/py/share/webcppcluster2025/service.py", line 11, in SendSvrd
    tcpCliSock.connect(ADDR)
ConnectionRefusedError: [Errno 111] Connection refused
2025-09-16 20:31:48|ERROR|Error.py|16|[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 154, in POST
    Lobby.SendMail(req)
  File "/home/py/share/webcppcluster2025/Lobby.py", line 55, in SendMail
    service.SendSvrd(Config.MAIL_HOST, Config.MAIL_PORT, mailproto.SerializeToString())
  File "/home/py/share/webcppcluster2025/service.py", line 11, in SendSvrd
    tcpCliSock.connect(ADDR)
ConnectionRefusedError: [Errno 111] Connection refused
2025-09-16 20:32:29|ERROR|Error.py|16|[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 154, in POST
    Lobby.SendMail(req)
  File "/home/py/share/webcppcluster2025/Lobby.py", line 55, in SendMail
    service.SendSvrd(Config.MAIL_HOST, Config.MAIL_PORT, mailproto.SerializeToString())
  File "/home/py/share/webcppcluster2025/service.py", line 11, in SendSvrd
    tcpCliSock.connect(ADDR)
ConnectionRefusedError: [Errno 111] Connection refused
2025-09-16 21:01:04|ERROR|Error.py|16|[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 154, in POST
    Lobby.SendMail(req)
  File "/home/py/share/webcppcluster2025/Lobby.py", line 55, in SendMail
    service.SendSvrd(Config.MAIL_HOST, Config.MAIL_PORT, mailproto.SerializeToString())
  File "/home/py/share/webcppcluster2025/service.py", line 28, in SendSvrd
    raise e
  File "/home/py/share/webcppcluster2025/service.py", line 13, in SendSvrd
    tcpCliSock.connect(ADDR)
ConnectionRefusedError: [Errno 111] Connection refused
2025-09-16 21:01:37|ERROR|Error.py|16|[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/py/share/webcppcluster2025/Error.py", line 14, in wrapper
    return func(*args, **kwargs)
  File "/home/py/share/webcppcluster2025/app.py", line 154, in POST
    Lobby.SendMail(req)
  File "/home/py/share/webcppcluster2025/Lobby.py", line 55, in SendMail
    service.SendSvrd(Config.MAIL_HOST, Config.MAIL_PORT, mailproto.SerializeToString())
  File "/home/py/share/webcppcluster2025/service.py", line 28, in SendSvrd
    raise e
  File "/home/py/share/webcppcluster2025/service.py", line 13, in SendSvrd
    tcpCliSock.connect(ADDR)
ConnectionRefusedError: [Errno 111] Connection refused
